# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDCFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDCFramework
   pod 'KXJsonUI'
    pod 'Alamofire', '~> 4.7'
    pod 'SCLAlertView'
    pod 'NVActivityIndicatorView'
    pod 'BiometricAuthentication'
    pod 'KeychainSwift', '~> 11.0'
    pod 'SwiftyJSON'
    pod 'DropDown'
    pod 'IQKeyboardManagerSwift'
    pod 'SwiftyGif'
    pod 'lottie-ios'
    pod 'SwiftyMenu', '~> 1.0.1'
    pod 'iOSDropDown', '0.3.4'
    pod 'SelectionList'
    pod 'DatePickerDialog'


end
